# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 670)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(440, 30, 200, 594))
        self.widget.setObjectName("widget")
        self.Attrlabel_Symbol = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Symbol.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.Attrlabel_Symbol.setObjectName("Attrlabel_Symbol")
        self.Attrlabel_Soutliecolor = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Soutliecolor.setGeometry(QtCore.QRect(30, 90, 81, 16))
        self.Attrlabel_Soutliecolor.setObjectName("Attrlabel_Soutliecolor")
        self.Attrlabel_Soutlinestyle = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Soutlinestyle.setGeometry(QtCore.QRect(30, 120, 81, 16))
        self.Attrlabel_Soutlinestyle.setObjectName("Attrlabel_Soutlinestyle")
        self.Attrlabel_Soutlinewidth = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Soutlinewidth.setGeometry(QtCore.QRect(30, 150, 81, 16))
        self.Attrlabel_Soutlinewidth.setObjectName("Attrlabel_Soutlinewidth")
        self.Attrlabel_Ssymbolcoor = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Ssymbolcoor.setGeometry(QtCore.QRect(30, 180, 81, 16))
        self.Attrlabel_Ssymbolcoor.setObjectName("Attrlabel_Ssymbolcoor")
        self.Attrlabel_Mark = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Mark.setGeometry(QtCore.QRect(20, 210, 81, 16))
        self.Attrlabel_Mark.setObjectName("Attrlabel_Mark")
        self.Attrlabel_Mvisible = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Mvisible.setGeometry(QtCore.QRect(30, 240, 81, 16))
        self.Attrlabel_Mvisible.setObjectName("Attrlabel_Mvisible")
        self.Attrlabel_Mfield = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Mfield.setGeometry(QtCore.QRect(30, 270, 81, 16))
        self.Attrlabel_Mfield.setObjectName("Attrlabel_Mfield")
        self.Attrlabel_Mxoffset = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Mxoffset.setGeometry(QtCore.QRect(30, 300, 81, 16))
        self.Attrlabel_Mxoffset.setObjectName("Attrlabel_Mxoffset")
        self.Attrlabel_Myoffset = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Myoffset.setGeometry(QtCore.QRect(30, 330, 81, 16))
        self.Attrlabel_Myoffset.setObjectName("Attrlabel_Myoffset")
        self.Attrlabel_Msymbolcolor = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Msymbolcolor.setGeometry(QtCore.QRect(30, 360, 81, 16))
        self.Attrlabel_Msymbolcolor.setObjectName("Attrlabel_Msymbolcolor")
        self.Attrlabel_Msize = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Msize.setGeometry(QtCore.QRect(30, 390, 81, 16))
        self.Attrlabel_Msize.setObjectName("Attrlabel_Msize")
        self.Attrlabel_Mcolor = QtWidgets.QLabel(self.widget)
        self.Attrlabel_Mcolor.setGeometry(QtCore.QRect(30, 420, 81, 16))
        self.Attrlabel_Mcolor.setObjectName("Attrlabel_Mcolor")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Attrlabel_Symbol.setText(_translate("Form", "符号"))
        self.Attrlabel_Soutliecolor.setText(_translate("Form", "OutlineColor"))
        self.Attrlabel_Soutlinestyle.setText(_translate("Form", "OutlineStyle"))
        self.Attrlabel_Soutlinewidth.setText(_translate("Form", "OutlineWidth"))
        self.Attrlabel_Ssymbolcoor.setText(_translate("Form", "SymbolColor"))
        self.Attrlabel_Mark.setText(_translate("Form", "注记"))
        self.Attrlabel_Mvisible.setText(_translate("Form", "可见性"))
        self.Attrlabel_Mfield.setText(_translate("Form", "绑定字段"))
        self.Attrlabel_Mxoffset.setText(_translate("Form", "水平偏移"))
        self.Attrlabel_Myoffset.setText(_translate("Form", "垂直偏移"))
        self.Attrlabel_Msymbolcolor.setText(_translate("Form", "SymbolColor"))
        self.Attrlabel_Msize.setText(_translate("Form", "字体大小"))
        self.Attrlabel_Mcolor.setText(_translate("Form", "字体颜色"))
