# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Win_NewLayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Win_NewLayer(object):
    def setupUi(self, Win_NewLayer):
        Win_NewLayer.setObjectName("Win_NewLayer")
        Win_NewLayer.resize(638, 443)
        self.label = QtWidgets.QLabel(Win_NewLayer)
        self.label.setGeometry(QtCore.QRect(150, 90, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Win_NewLayer)
        self.lineEdit.setGeometry(QtCore.QRect(310, 90, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Win_NewLayer)
        self.label_2.setGeometry(QtCore.QRect(150, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Win_NewLayer)
        self.comboBox.setGeometry(QtCore.QRect(310, 150, 111, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.bt_OK = QtWidgets.QPushButton(Win_NewLayer)
        self.bt_OK.setGeometry(QtCore.QRect(120, 310, 93, 28))
        self.bt_OK.setObjectName("bt_OK")
        self.bt_Cancel = QtWidgets.QPushButton(Win_NewLayer)
        self.bt_Cancel.setGeometry(QtCore.QRect(400, 310, 93, 28))
        self.bt_Cancel.setObjectName("bt_Cancel")

        self.retranslateUi(Win_NewLayer)
        QtCore.QMetaObject.connectSlotsByName(Win_NewLayer)

    def retranslateUi(self, Win_NewLayer):
        _translate = QtCore.QCoreApplication.translate
        Win_NewLayer.setWindowTitle(_translate("Win_NewLayer", "创建新图层"))
        self.label.setText(_translate("Win_NewLayer", "图层名字"))
        self.label_2.setText(_translate("Win_NewLayer", "要素类型"))
        self.comboBox.setItemText(0, _translate("Win_NewLayer", "点"))
        self.comboBox.setItemText(1, _translate("Win_NewLayer", "线"))
        self.comboBox.setItemText(2, _translate("Win_NewLayer", "面"))
        self.comboBox.setItemText(3, _translate('Win_NewLayer', "多线"))
        self.comboBox.setItemText(4, _translate('Win_NewLayer', "多面"))
        self.bt_OK.setText(_translate("Win_NewLayer", "确定"))
        self.bt_Cancel.setText(_translate("Win_NewLayer", "取消"))
