# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Win_SelectByAttr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Win_SelectByAttr(object):
    def setupUi(self, Win_SelectByAttr):
        Win_SelectByAttr.setObjectName("Win_SelectByAttr")
        Win_SelectByAttr.resize(360, 330)
        self.bt_OK = QtWidgets.QPushButton(Win_SelectByAttr)
        self.bt_OK.setGeometry(QtCore.QRect(80, 240, 81, 41))
        self.bt_OK.setObjectName("bt_OK")
        self.bt_Cancel = QtWidgets.QPushButton(Win_SelectByAttr)
        self.bt_Cancel.setGeometry(QtCore.QRect(190, 240, 81, 41))
        self.bt_Cancel.setObjectName("bt_Cancel")
        self.layoutWidget = QtWidgets.QWidget(Win_SelectByAttr)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 258, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_layer = QtWidgets.QLabel(self.layoutWidget)
        self.label_layer.setObjectName("label_layer")
        self.gridLayout.addWidget(self.label_layer, 0, 0, 1, 1)
        self.comboBox_SelectMode = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_SelectMode.setObjectName("comboBox_SelectMode")
        self.comboBox_SelectMode.addItem("")
        self.comboBox_SelectMode.addItem("")
        self.comboBox_SelectMode.addItem("")
        self.comboBox_SelectMode.addItem("")
        self.gridLayout.addWidget(self.comboBox_SelectMode, 2, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_type.sizePolicy().hasHeightForWidth())
        self.label_type.setSizePolicy(sizePolicy)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 2, 0, 1, 1)
        self.combo_layer = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_layer.setObjectName("combo_layer")
        self.gridLayout.addWidget(self.combo_layer, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.label_SelectTitle = QtWidgets.QLabel(self.layoutWidget)
        self.label_SelectTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_SelectTitle.setObjectName("label_SelectTitle")
        self.verticalLayout.addWidget(self.label_SelectTitle)
        self.lineEdit_SelectState = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SelectState.setObjectName("lineEdit_SelectState")
        self.verticalLayout.addWidget(self.lineEdit_SelectState)

        self.retranslateUi(Win_SelectByAttr)
        QtCore.QMetaObject.connectSlotsByName(Win_SelectByAttr)

    def retranslateUi(self, Win_SelectByAttr):
        _translate = QtCore.QCoreApplication.translate
        Win_SelectByAttr.setWindowTitle(_translate("Win_SelectByAttr", "SelectByAttribute"))
        self.bt_OK.setText(_translate("Win_SelectByAttr", "确定"))
        self.bt_Cancel.setText(_translate("Win_SelectByAttr", "取消"))
        self.label_layer.setText(_translate("Win_SelectByAttr", "图层"))
        self.comboBox_SelectMode.setItemText(0, _translate("Win_SelectByAttr", "创建新的选择集"))
        self.comboBox_SelectMode.setItemText(1, _translate("Win_SelectByAttr", "加入当前选择集"))
        self.comboBox_SelectMode.setItemText(2, _translate("Win_SelectByAttr", "从当前选择集中移除"))
        self.comboBox_SelectMode.setItemText(3, _translate("Win_SelectByAttr", "从当前选择集中选择"))
        self.label_type.setText(_translate("Win_SelectByAttr", "选择方式"))
        self.label_SelectTitle.setText(_translate("Win_SelectByAttr", "Select* FROM 图层名 WHERE:"))
