# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Win_DBLoad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Win_DBLoad(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(489, 555)
        self.DBL_tableWidget = QtWidgets.QTableWidget(Form)
        self.DBL_tableWidget.setGeometry(QtCore.QRect(50, 40, 381, 391))
        self.DBL_tableWidget.setObjectName("DBL_tableWidget")
        self.DBL_tableWidget.setColumnCount(2)
        self.DBL_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DBL_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DBL_tableWidget.setHorizontalHeaderItem(1, item)
        self.DBLoad_OK = QtWidgets.QPushButton(Form)
        self.DBLoad_OK.setGeometry(QtCore.QRect(100, 470, 91, 51))
        self.DBLoad_OK.setObjectName("DBLoad_OK")
        self.DBLoad_Cancel = QtWidgets.QPushButton(Form)
        self.DBLoad_Cancel.setGeometry(QtCore.QRect(270, 470, 91, 51))
        self.DBLoad_Cancel.setObjectName("DBLoad_Cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DBLoad"))
        item = self.DBL_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "图层名称"))
        item = self.DBL_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "图层类型"))
        self.DBLoad_OK.setText(_translate("Form", "确定"))
        self.DBLoad_Cancel.setText(_translate("Form", "取消"))
